/** This file is auto-generated by Plasmic; please do not edit! */

<script>
!function(){const n=window,i="__REACT_DEVTOOLS_GLOBAL_HOOK__",o="__PlasmicPreambleVersion",t=function(){}
if(void 0!==n){if(n.parent!==n)try{n[i]=n.parent[i]}catch(e){}if(!n[i]){const r=new Map
n[i]={supportsFiber:!0,renderers:r,inject:function(n){r.set(r.size+1,n)},onCommitFiberRoot:t,onCommitFiberUnmount:t}}n[i][o]||(n[i][o]="1")}}()
</script>

import * as React from 'react';
import PlasmicLoader from '@plasmicapp/loader';

export default function PageComponent() {
    return <PlasmicLoader projectId="tTTfyagU4BsuSpRcQ5wFNN" component="Homepage"  />
}